urls:
  api: 'https://api.multiversx.com'
  swagger:
    - 'https://production-itheum-api.up.railway.app'
itheumSdk.environment: 'mainnet'
api:
  auth: true
features:
  publicApi:
    enabled: true
    port: 3000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - 'datadex.itheum.io'
    - 'https://stg.datadex.itheum.io'
    - 'https://datadex.itheum.io'
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
