urls:
  api: "https://devnet-api.multiversx.com"
  swagger:
    - "http://localhost:3000"
itheumSdk.environment: "devnet"
api:
  auth: true
features:
  publicApi:
    enabled: true
    port: 3000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - "datadex.itheum.io"
    - "https://stg.datadex.itheum.io"
    - "https://test.datadex.itheum.io"
    - "stg.datadex.itheum.io"
    - "https://datadex.itheum.io"
    - "https://utils.multiversx.com"
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
